version: 2.1
jobs:
  test:
    environment:
      TZ: "Asia/Tokyo"
    docker:
      - image: circleci/python:3.7
    steps:
    - checkout
    - run:
        name:
        command: |
          echo spam
workflows:
  dummy_test:
    jobs:
      - test
